### ISSUE TITLE
Module not loading

### ISSUE THREAD

**Issue by RobinKnipe** [Nordstrom/artillery-plugin-http-ssl#4]
I'm getting the following message from `artillery`, but sadly no other information:
```
WARNING: plugin http-ssl specified but module artillery-plugin-http-ssl could not be loaded
```

I have `artillery` and this plugin installed locally:
```
npm i artillery
npm i artillery-plugin-http-ssl
```

...and have the following config (adapted from the example in the README):
```
config:
  tls:
    rejectUnauthorized: false
    cert: "{{ CLIENT_CERT }}"
    key: "{{ CLIENT_KEY }}"
  plugins:
    http-ssl: {}
...
```

**Comment by RobinKnipe** [comment]
To solve my own issue... and in the hopes that someone else finds it useful...

Simply declaring the `plugins` section before the `tls` config seems to work:
```
config:
  plugins:
    http-ssl: {}
  tls:
    rejectUnauthorized: false
    cert: "{{ CLIENT_CERT }}"
    key: "{{ CLIENT_KEY }}"
...
```
